version: "3.3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: ubuntu:16.04
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:80"
    networks:
      - webnet
    command: tail -f /dev/null

networks:
  webnet:
    external:
      name: goblintown_webnet
