version: "3.3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: ubuntu:16.04
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - default
    volumes:
      - ./:/opt/goblintown:ro
    command: >
      bash -lc "apt-get update 
      && apt-get install --reinstall dbus -y  
      && apt-get install software-properties-common -y   
      && apt-add-repository ppa:ansible/ansible 
      && apt-get update && apt-get install ansible -y 
      && ansible-playbook /opt/goblintown/ansible/goblintown.yml 
      && cd /opt/goblintown/app 
      && python3 app.py"
networks:
  default:
